#!/bin/sh

: ${C_FLAG:=0}
: ${K_FLAG:=0}
: ${OPT_ERROR=0}
while getopts "ckhf:" opts
do
	case $opts in
		c)
			C_FLAG=1
			;;
		k)
			K_FLAG=1
			;;
		f)
			TARGET_FILE=$OPTARG
			;;
		h)
			OPT_ERROR=1
			;;
		\?)
			OPT_ERROR=1
			break
			;;
	esac
done


if [ $C_FLAG -eq "1" ] && [ $K_FLAG -eq "1" ];
then
	OPT_ERROR=1
fi

if [ $OPT_ERROR -eq "1" ];
then
	cat << __EOT__
USAGE:
$0 {-c|-k} -f <TARGET_FILE>

-c	change KUTOUTEN into comma/period
-k	change comma/period into KUTOUTEN

TARGET_FILE must be defined with -f option.
__EOT__
	exit 1
fi

if [ -z $TARGET_FILE ];
then
	echo "TARGET FILE must be defined with -f option."
	exit 1
fi

if [ $C_FLAG -eq "1" ];
then
	echo "ファイル $TARGET_FILE の中の句読点をコンマとピリオドに変換します。"
	sed -i "-bak" -e "s/、/，/g" -e "s/。/．/g" $TARGET_FILE
fi

if [ $K_FLAG -eq "1" ];
then
	echo "ファイル $TARGET_FILE の中のコンマとピリオドを句読点に変換します。"
	sed -i "-bak" -e "s/，/、/g" -e "s/．/。/g" $TARGET_FILE
fi


exit 0
